visualize-admin/electricity-prices-switzerland

src/graphql/queries.graphql, src/graphql/queries.ts, src/graphql/resolver-types.ts, src/graphql/resolvers.ts, src/graphql/schema.graphql, src/pages/_system/api-status.tsx
Map was not working because of missing dimensions in the cube shape
(only on lindas cached, not on normal lindas). Here I added a cube
health endpoint whose result is shown on the api-status page.
This way, we can check if all the dimensions are there. Since this
page is monitored by betteruptime, we will be warned if it ever
happens again.﻿
=> Add cube health to status page

src/components/info-banner.tsx, src/graphql/queries.graphql, src/graphql/queries.ts, src/graphql/resolver-types.ts, src/graphql/resolvers.ts, src/graphql/schema.graphql, src/pages/index.tsx
A banner whose content is configured in the wiki can be activated
or deactivated from the wiki.
Now, it is shown also when no median value can be found in the
data.
=> Automatically show banner if data not available

package.json, src/domain/gever/message.ts, src/graphql/resolvers.ts, src/pages/_system/api-status.tsx, src/pages/api/debug-download.ts, src/rdf/search-queries.ts, src/rdf/sparql-client.ts, src/server/nextkit.ts, yarn.lock
Since the download document process is so convoluted, I made a route that gives us more information on each step.
First, if the conversion from OID (275) to UID (CHE-100-000-11) through Lindas was succesful, then the search request and response. Also there are the endpoints used for the SAML requests. The route is protected by a password (stored in 1Password and changeable through environment variable).
=> feat: Add document download debug

src/components/footer.tsx, src/locales/de/messages.po, src/locales/fr/messages.po, src/locales/it/messages.po
Add an icon opening a dialog containing help content (content fetched on Gitlab)
=> feat: Add help icon opening dialog containing help content

src/components/operator-documents.tsx, src/graphql/queries.graphql, src/graphql/resolvers.ts
Remove legacy documents now that documents are provided via the GEVER database.
=> feat: Remove displaying and querying legacy documents from old database

src/pages/api/data-export.ts
As a consumer, I would like to receive additional tariff data that I can evaluate. I would like to receive the following additional data - for grid and energy - in addition to the existing csv data:
Grundpreis
1. Leistungspreis: power price
2. Arbeitspreis: working price
3. Rabatte: discount
=> New columns in CSV download

src/components/map.tsx
For cases where there are multiple operator, we need to consider the
mean, otherwise there can be a discrepancy between the extent of thelegend
and the municipality list.
Zurich has prices 1, 7
Bale has prices 3
If we do not consider the mean for the legend, we have min,max = 1, 7, while in the municipality list it will be written Zurich 4 ((1 + 7) / 2) , Bale 3.
For legend to be in cohere with municipality list it needs to do the mean, so that it shows min, max = 1, 4
1. Open https://www.strompreis.elcom.admin.ch/?category=H1&period=2024
2. Sort municipalities by "Teuerste zuerst"
3. See that most expensive municipality has price 55.45, while legend has price 64
1. Open https://elcom-electricity-price-website-git-fix-coherence-legend-ixt1.vercel.app/?vercelToolbarCode=EhekYW-4HrPwWZ_&peri …
=> fix: Coherence between municipality list and map legend

.env.development, README.md, src/env/schema.js, src/rdf/queries.ts
Now that we use the lindas cluster endpoint, we can add the cube iri to the endpoint,
this way, we use a cache that is only updated when the cube's is updated, not when
*any* cube is updated.
=> feat: Adds support for endpoints that can cache their results per cube

.github/workflows/gitlab-mirror.yml
This PR fixes broken GitLab mirroring by changing the action we use and updating deploy tokens.
=> fix: GitLab mirror

src/components/charts-generic/constants.ts, src/components/charts-generic/histogram/histogram-state.tsx
Closes #63 
This PR improves the tooltip positioning for the histogram Chart by increasing the offset from `10 -> 30`
1. Go to this [link](https://elcom-electricity-price-website-git-fix-tooltip-ori-ed2b7e-ixt1.vercel.app/municipality/1402).
2. Scroll down to histograms
3. Hover over the chart
4. See how tooltip is overlapping the smaller bars and is aligned to the top of them ✅ 
1. Go to this [link](https://www.strompreis.elcom.admin.ch/municipality/1406)
2. Scroll down to histograms
5. Hover over the chart
6. See how tooltip is overlapping the smaller bars and is not aligned to the top of them ❌ 
---
---
cc: @sosiology
=> fix: Fixed tooltip positioning w/ increased offset

.storybook/preview.tsx, knip.config.ts, src/components/combobox.stories.tsx, src/components/combobox.tsx, src/components/detail-page/layout.tsx, src/components/map.stories.tsx, src/data/shared-page-props.tsx, src/pages/[entity]/[id]/index.tsx, src/rdf/queries.ts
Refactor the electricity tariffs page
Make the layout & props easier to reuse.
The electricity tariffs page reuses the details page layout components.
The sunshine pages will be able to use this details page layout.
=> Refactor details page

src/components/button-group.stories.tsx, src/components/card-grid.stories.tsx, src/components/card-grid.tsx, src/components/card-source.tsx, src/components/combobox.stories.tsx, src/components/comparison-table.stories.tsx, src/components/comparison-table.tsx, src/components/detail-page/sidebar.tsx, src/components/kitchen-sink.stories.tsx, src/components/net-tariffs-trend-card.tsx, src/components/network-costs-trend-card.tsx, src/components/peer-group-card.tsx, src/components/storybook/story-grid.tsx, src/components/table-comparison-card.tsx, src/components/unit-value-with-trend.tsx, src/data/shared-page-props.tsx, src/domain/data.ts, src/domain/translation.tsx, src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
Add costs and tariffs page
The goal of this PR is to have the components and structure ready to implement the other sunshine pages.
I tried to have in the end the individual sunshine tabs as short as possible since there are many which
will only change barely between tabs. Hence the introduction of shared components:
- PeerGroupCard
- TableComparisonCard
- CardGrid
- Data is mocked, will get better soon in another PR
- Other pages will be implemented, data will be mocked at graphql level
-
=> Add costs and tariffs page

CHANGELOG.md, src/components/charts-generic/bars/bars-stacked-state.tsx, src/components/combobox.stories.tsx, src/components/combobox.tsx, src/components/detail-page/selector-multi.tsx, src/components/kitchen-sink.stories.tsx, src/components/net-tariffs-trend-card.tsx, src/components/net-tariffs-trend-chart.tsx, src/components/network-cost-trend-chart.tsx, src/components/network-costs-trend-card.tsx, src/components/power-stability-card.tsx, src/components/power-stability-chart.tsx, src/components/query-combobox.tsx, src/components/scatter-plot.stories.tsx, src/domain/helper.spec.ts, src/domain/helpers.tsx, src/domain/translation.tsx
This PR adds new Select all or use MultiCombobox and integrates it with the scatterplot charts on costs and tariffs
1. Navigate to this [link](https://elcom-electricity-price-website-git-feat-connect-th-638c7c-ixt1.vercel.app/sunshine/operator/486/costs-and-tariffs)
2. Click on Compared with `MultiCombobox` 
3. ✅ See how when you select other operators, `Select all` is no longer used
4. ✅ See how when removing all operators, automatically `Select all` is used
5. ⚠️ Select a lot of operators see how large `MultiCombobox` gets 
cc. @ptbrowne future PR will include moving the layout to the new design, additionally naming conventions from the data `period` or `year` `operator_id` or `operator` might be a good refactor but not urgent
Discussing whether this is optimal behaviour can be …
=> Connect MultiCombobox with Sunshine pages

CHANGELOG.md, e2e/sunshine.spec.ts, src/components/charts-generic/interaction/latest-indicator.tsx, src/components/detail-page/price-evolution-line-chart.tsx, src/components/map-details-content.tsx, src/components/sunshine-tabs.tsx
This PR adds the missing latest year indicator to the mini chart on the map details panel.
=> Latest year indicator for mini charts

CHANGELOG.md, package.json, scripts/wiki-content.ts, src/components/button-group.tsx, src/components/combobox.stories.tsx, src/components/combobox.tsx, src/components/info-dialog.tsx, src/components/network-costs-trend-card.tsx, src/domain/data.ts, src/domain/gitlab-wiki-api.ts, src/graphql/resolvers.ts, src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx, src/pages/sunshine/[entity]/[id]/power-stability.tsx, src/utils/flags.ts, yarn.lock
- Add types for wiki pages
- Add way to update those types automatically by listing pages from wiki
- Add flag to show which wiki page slug is behind which button. flag__debugInfoDialog=true
- Fix some of the slug used 
Should open a new issue for @mevionfamos with pages that are not in wiki yet.
```
missing: [
// costs and tariffs page, net tariff tab
"help-net-tariffs",
"help-net-tariff-category",
// costs and tariffs page, energy tariff tab
"help-energy-tariff-category",
// map page, selector panel
"help-indicator",
"help-typology",
"help-network-level",
// To check later, page is being improvedv
"help-operational-standards",D
],
```
- Feature flags: flag__debugInfoDialog
Missing pages should be added to wiki
=> Wiki info slugs

knip.config.ts, src/components/generic-map.tsx, src/components/map-helpers.spec.ts, src/components/map-helpers.tsx, src/flags/index.ts, src/pages/map/index.tsx
Fix an annoying application error that would trigger sometimes on page change.
Added defensive code around map zoom and also made the code to fit bounds a bit more robust by decreasing padding step by step.
=> Fix map zoom

CHANGELOG.md, src/components/generic-map.tsx, src/locales/aa/messages.po, src/locales/de/messages.po, src/locales/en/messages.po, src/locales/fr/messages.po, src/locales/it/messages.po
On the sunshine map, the map is hijacking the scroll from the user.
It is an annoying behavior. The usual behavior for this type of maps is
to only allow scrolling if the user is holding some key.
This is what's implemented here.
1. Go to the map
2. Scroll the page, see how the scroll is not taken by the map
3. See the help
4. Follow the help and see that you can scroll the map
Additionally, the scroll to zoom is not that interesting when users can
zoom to their municipality or canton via the list.
Google Map documentation: they allow to opt out of this behavior via
gestureHandling: greedy.
https://developers.google.com/maps/documentation/javascript/interaction
=> Scroll zoom on map

src/env/client.ts, src/env/schema.ts, src/pages/_app.tsx, src/pages/api/flags.ts, src/utils/flags.ts
I had made a logic mistake before: in order for the flags to be set at runtime
through process.env, they should not be set via NEXT_PUBLIC (as those are
compiled through webpack, and then they cannot be changed directly at runtime).
Here, I add an /api route serving the runtime flags, and the flags are set
if they do not already have a value.
=> feat: Server side flags to allow for changing runtime flags

src/components/charts-generic/progress-overtime-chart.tsx, src/components/network-cost-trend-chart.tsx, src/components/operator-documents.stories.tsx, src/components/operator-documents.tsx, src/components/power-stability-chart.tsx, src/components/sunshine-tabs.tsx, src/components/table-comparison-card.tsx, src/components/tariffs-trend-chart.tsx, src/graphql/queries.graphql, src/graphql/queries.ts, src/graphql/resolver-types.ts, src/graphql/resolvers.ts, src/graphql/schema.graphql, src/lib/db/sparql.integration.spec.ts, src/lib/db/sparql.ts, src/lib/db/sql.ts, src/lib/sunshine-data-service.ts, src/lib/sunshine-data.ts, src/pages/sunshine/[entity]/[id]/operational-standards.tsx, src/pages/sunshine/[entity]/[id]/overview.tsx
Operator documents
- **refactor: Extract OperatorDocumentsPopoverContent to have it inside Storybook**
- **feat: Allow scrolling for OperatorDocuments**
- **feat: Remove id of operator in operator documents popover content**
- **refactor: Extract OperatorDocumentsPopoverContent to have it inside Storybook**
Informing customers about outages
- **fix: Do not convert boolean value as string otherwise it is always true**
Chart improvements
- **refactor: Remove showInteractionsWhenComparing & showOtherOperatorsLegend**
Peer median calculation fixes
- **refactor: Rename getIndicatorMedian into getYearlyIndicatorMedians**
- **fix: Correctly filter by peer group for median calculation**
- **feat: Make the TableComparisonCard less knowing about the year**
- **refactor: Destructure props early** …
=> Overview improvements

.github/workflows/e2e.yml, CHANGELOG.md, e2e/common.ts, e2e/map.spec.ts, package.json, src/components/detail-page/download-image.tsx, src/components/generic-map.tsx, src/components/share-button.tsx, src/domain/screenshot.ts, src/pages/map/index.tsx
Due to a refactoring in 338d5883bf04216d5d4e172e1c69e498dc77a5f1, the legend
id was not correctly passed to the legend item, and it would break the
screenshotting functionality of the map.
closes #325
1. Navigate to the map
2. Click the download button, an image should be downloaded
3. Switch to sunshine indicators and verify that it also works
=> fix: Map image can be downloaded

src/pages/map/index.tsx
Fix https://github.com/visualize-admin/electricity-prices-switzerland/issues/179#issuecomment-3228795753
- Go the map, see the layout is "full-bleed", it extends to the side of the browser viewport
- Go to the details page, see that the layout width is constrained to ~1420px
=> feat: Map takes the whole width of the page

CHANGELOG.md, src/pages/index.tsx
This PR resolves a bug where the language would revert back to DE (default) when clicking the main CTA button on the overview page. 
Fixes #345 
1. Navigate to `/`
2. Change the language to italian
3. Click on the primary CTA: "Tariffe elettriche in Svizzera"
4. Observe you go to `/it/map` instead of `/map` and the language is still italian
=> Preserve language when clicking main CTA button

src/components/detail-page/cantons-comparison-range.tsx, src/components/detail-page/price-distribution-histogram.tsx, src/domain/data.ts, src/domain/query-states.ts
This PR changes the order of the price components in the map drop down and on the detail page, as per ElCom's request. The order should be: 
- total
- grid usage
- metering cost / rate
- energy cost
- charge
- aidfee
It also fixes a bug where the details page was validating against the wrong priceComponent schema. 
1. Navigate to https://elcom-electricity-price-website-git-fix-price-compo-70e367-ixt1.vercel.app/municipality/3871?period=2026&priceComponent=meteringrate&municipality=6621%2C1301
2. Observe the order is updated
3. Scroll to "Preisverteilung in der Schweiz"
4. Select "Messtarif"
5. Observe it works now
Affects:
I forgot to open a ticket for this. Looks to me that we can only change the order in data.ts and the toggle group components but I'll need to test if this affects other …
=> Re-order price components

CHANGELOG.md, src/pages/_app.tsx, src/utils/flags.ts
- **refactor: Detangle hooks**
- **feat: Ability to deactivate manual locale activation**
This PR introduces a flag that can bypass a locale activation logic based
on the URL. 
This activation logic seems buggy since it relies on an heuristic to detect
the locale (searches for <locale> in the URL), and fails to return the correct
locale in case of localised domains.
=> Fix locale glitch
