visualize-admin/electricity-prices-switzerland

- .env.development
- src/components/SectionContentContainer.tsx
- src/components/charts-generic/interaction/tooltip-box.tsx
- src/components/detail-page/banner.tsx
- src/components/detail-page/download-image.tsx
- src/components/detail-page/layout.tsx
- src/components/footer.tsx
- src/components/header.tsx
- src/components/info-banner.tsx
- src/components/info-dialog.tsx
- src/components/useDisclosure.tsx
- src/components/useOutsideClick.tsx
- src/docs/icons.docs.tsx
- src/icons/ic-download.tsx
- src/icons/index.tsx
- src/locales/de/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
- src/pages/_app.tsx
- src/pages/docs.tsx
- src/pages/index.tsx
- src/themes/elcom.ts
Fix #60 
- Added external links
- Added share popover
- Add max width to page (important for large screens)
> Footer redesign

- .gitignore
- README.md
- e2e/generate-k6-har.spec.ts
- e2e/utils.ts
- package.json
- playwright.config.ts
See the README for the explanation.
- feat: Generate HAR from Playwright
- docs: Added docs
- docs: Add how to edit the test
- docs: Update docs
> Docs: Load test

- src/locales/de/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
Updated links to opendata.swiss in the footer.
> Footer links

- .github/pull_request_template.md
> chore: Added the PR template from visualize

- src/components/combobox.tsx
- src/components/detail-page/banner.tsx
- src/components/detail-page/cantons-comparison-range.tsx
- src/components/detail-page/card.tsx
- src/components/detail-page/download-image.tsx
- src/components/detail-page/filter-set-description.tsx
- src/components/detail-page/price-components-bars.tsx
- src/components/detail-page/price-distribution-histogram.tsx
- src/components/detail-page/price-evolution-line-chart.tsx
- src/components/info-dialog.tsx
- src/components/map.tsx
- src/components/price-color-legend.tsx
- src/components/radio-tabs.tsx
- src/pages/municipality/[id].tsx
This PR improves general components within the codebase improving the overall structure and reusability.
No particular issue to relate to. 
cc: @ptbrowne I think like this we have slightly improved reusable components, additionally it improves readability with named components understanding the structure with just a glance.
> refactor: Improves layout overall structure 

- src/themes/palette.ts
This PR implements the ci/cd colors based on the clients needs
No particiular issues
cc: @AnninaWalker checkout the changes [here](https://elcom-electricity-price-website-git-refactor-client-cdbe37-ixt1.vercel.app/)
> fix: new ci/cd colors after clients feedback

- package.json
- src/components/header.tsx
- src/flags/api.tsx
- src/flags/components.tsx
- src/flags/hooks.ts
- src/flags/index.ts
- src/flags/ls-adapter.ts
- src/flags/store.ts
- src/flags/types.ts
- src/utils/flags.ts
- yarn.lock
- Fixes https://github.com/visualize-admin/electricity-prices-switzerland/issues/169
1. Go to https://elcom-electricity-price-website-git-feat-flags-ixt1.vercel.app/?flag__debug=true
2. See that you have a flags menu at the top
3. Go to https://elcom-electricity-price-website-git-feat-flags-ixt1.vercel.app/?flag__debug=false
4. No menu "flags" at the top
> feat: Add possibility to have flags

- src/components/app-layout.tsx
- src/components/list.tsx
- src/components/operator-documents.tsx
- src/components/search.tsx
- src/locales/de/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
- src/themes/components.tsx
This PR adds Operators Downlaod back 
cc: Can't be tested -> there are no operator documents
> Last fixes before final merge

- .github/ISSUE_TEMPLATE/testing_feedback.md
I'm adding a template for general feedback that includes fields for testing environment, device, reproduction steps, etc. 
```markdown
1. Navigate to ...
2. Click on ...
3. Observe ...
- Browser:
- Device:
- OS:
- Version:
```
> chore: Add testing feedback template

- src/components/map.stories.tsx
- src/data/geo.spec.tsx
- src/data/geo.tsx
- Extract getOperatorsFeatureCollection so that it can be used elsewhere
- Add tests for getOperatorsFeatureCollection logic
This way Noah, the operator layer can be used in the details view.
> Extract getOperatorsFeatureCollection

- src/components/map.stories.tsx
Missing MapProvider made the map story fail.
> fix: Map story missing decorator

- CHANGELOG.md
- package.json
- yarn.lock
This PR updates `tpo-deepl `to v1.2.4 supporting the new `duplicates` command allowing to detecting duplicates within `msgstr` with `fuzziness`, `language` and `strict` options. [Read more](https://www.npmjs.com/package/tpo-deepl)
No particular issue
cc: @ptbrowne could be useful to have along side knip also for ci I plan to add auto resolving for duplicates feature soon
> chore: updated tpo

- src/components/horizontal-bar-chart.stories.tsx
- src/components/net-tariffs-trend-card.tsx
- src/components/net-tariffs-trend-chart.tsx
- src/components/network-cost-trend-chart.tsx
- src/components/network-costs-trend-card.tsx
- src/components/power-stability-card.tsx
- src/components/power-stability-chart.tsx
- src/components/scatter-plot.stories.tsx
- src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
- src/pages/sunshine/[entity]/[id]/power-stability.tsx
This PR adds rendering logic and cleans up the previous PR recommendations.
cc: @ptbrowne next PR I will do some refactoring on all chart types Also for some reason each commit is duplicated so you can start on [commit 6](https://github.com/visualize-admin/electricity-prices-switzerland/pull/246/commits/51e4b46611c7c6cfa3bc35bbe4a811e9616bc60a)
> Feat: Added rendering logic and cleaned up a bit

- CHANGELOG.md
- src/components/charts-generic/bars/bars-grouped-state.tsx
- src/components/charts-generic/bars/bars-grouped.tsx
- src/components/charts-generic/constants.ts
- src/components/detail-page/price-components-bars.tsx
- src/components/hint.tsx
- src/components/info-banner.tsx
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
- src/utils/flags.ts
This PR adds dynamic tariffs to the price component section.
resolves #164 
cc: @ptbrowne not sure how closely this aligns with how the data comes.
> Dynamic Tariffs

- CHANGELOG.md
- src/components/detail-page/card.tsx
- src/components/horizontal-bar-chart.stories.tsx
- src/components/map-details-chart-adapters.tsx
- src/components/network-cost-trend-chart.tsx
- src/components/network-costs-trend-card.tsx
- src/components/power-stability-card.tsx
- src/components/power-stability-chart.tsx
- src/components/scatter-plot.stories.tsx
- src/components/sunshine-tabs.tsx
- src/components/table-comparison-card.tsx
- src/components/tariffs-trend-card.tsx
- src/components/tariffs-trend-chart.tsx
- src/domain/query-states.ts
- src/domain/translation.tsx
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
- src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
- src/pages/sunshine/[entity]/[id]/operational-standards.tsx
- src/pages/sunshine/[entity]/[id]/overview.tsx
- src/pages/sunshine/[entity]/[id]/power-stability.tsx
This PR adds the overview details page 
Related to #262 
- refactor to use query states 
- refactor to use years filter properly + add operational standards query
> Implement Overview Details Page

- src/components/sunshine-map.tsx
- src/lib/sunshine-data.ts
- src/pages/api/sunshineDataService.ts
- src/pages/sunshine/[entity]/[id]/overview.tsx
- src/pages/sunshine/[entity]/[id]/power-stability.tsx
This PR improves the user experience and data handling in the Sunshine application by:
- Adding loading states to the Sunshine map component to prevent rendering with incomplete data
Improving null safety for SAIDI/SAIFI data by adding proper null checks and fallback values
- After setting the service key via the API, the user is directly redirected to the sunshine map
- Adding defensive rendering for overview cards to handle missing data gracefully
- Providing user feedback when power stability data is unavailable
> Improvements 1

- CHANGELOG.md
- src/components/charts-generic/interaction/tooltip-box.tsx
- src/components/energy-prices-map.tsx
- src/components/map-helpers.tsx
- src/components/map-layers.tsx
- src/components/sunshine-map.tsx
- **refactor: Extract map layers to its own file**
- **feat: Align map effect between sunshine and energy prices**
- **refactor: Shared helpers for common layers**
- **docs: Update changelog**
- **chore: Knip**
> Map consolidation

- src/locales/aa/messages.po
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
> chore: sync translations

- src/locales/de/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
Updating latest accent strings and addressing client request from [PELCOMDB-2497](https://jira.uvek.admin.ch/jira/browse/PELCOMDB-2497)
#308 
We may keep this PR open for now, as I might continue to make changes to the strings over the coming weeks and squash these commits later. 
There are some inconsistencies in how the msg IDs for compliance and operational standards are used throughout the app, which makes it a bit tricky to separate them at the moment. I have noted it down in [notion](https://www.notion.so/interactivethings/Testing-Document-22930da54302804b86b3c7d1dc2ebd04?source=copy_link#23f30da5430280479245e8eff4bbf8b4) and  it may be addressed at a later stage
> Update Accent strings

- CHANGELOG.md
- src/components/button-group.stories.tsx
- src/components/button-group.tsx
- src/components/combined-selectors/index.tsx
- src/components/detail-page/cantons-comparison-range.tsx
- src/components/detail-page/price-components-bars.tsx
- src/components/detail-page/price-distribution-histogram.tsx
- src/components/network-costs-trend-card.tsx
- src/components/power-stability-card.tsx
- src/components/tariffs-trend-card.tsx
- src/domain/translation.tsx
- src/locales/aa/messages.po
- src/locales/de/messages.po
- src/locales/en/messages.po
- src/locales/fr/messages.po
- src/locales/it/messages.po
This PR adds custom dynamically addable tooltips to the button groups component. No additionally explanation where added to the button groups however the capability is done.
This relates to the client feedback in https://www.notion.so/interactivethings/ElCom-Design-Feedback-for-Sunshine-25a30da5430280749ca9f0e8ecd2fc8d?source=copy_link
> Refactored Button Groups for Improved Tooltips

- src/components/hint.stories.tsx
Showing all the hints in Storybook.
> feat: Add hint stories
